const timeline = [
  {
    span: '2023-present',
    title: 'software engineer',
    company: 'neusort',
    description: `Architected and developed a distributed enterprise interview platform using Node.js, Go, Azure, and WebRTC, including real-time video processing, AI-powered coding assessments (EvalAI), intelligent load balancing, timezone-independent booking systems, payment integration, HR analytics dashboards, and automated CI/CD pipelines with cloud provisioning.`,
    companySite: 'https://www.neusort.com',
  },
];
const skills = [
  'JavaScript',
  'TypeScript',
  'Python',
  'GO',
  'HTML',
  'CSS',
  'SQL',
  'Node',
  'Prisma',
  'Express',
  'Next',
  'Tailwind',
  'React',
  'React-Native',
  'Azure',
  'Firebase',
  'CI/CD',
  'OOP',
  'Linux',
  'NoSQL',
  'Git',
  'Redis',
  'RabbitMQ',
  'REST',
  'WebSockets',
  'Database Design',
  'Docker',
  'Microservices',
  'Distributed Systems',
  'Frontend',
  'Backend',
  'Full-Stack',
];

export { skills, timeline };
